### ISSUE TITLE
New spam doesn't get caught

### ISSUE THREAD

**Issue by kokotas89** [andshiga/spamFilter#1]
Seems spammers have caught on... I received two new emails in my inbox as such

title:
Confirm->HomeWarranty#3551601

from:
servicePlus <_KIHZNUUPIE@smivapcsjyzndezekq.edu> [via](https://support.google.com/mail/answer/1311182?hl=en) netorgft12811114.onmicrosoft.com

replay to:
OWEDBBNXICP57ICZWRNM9YOJLHTR57@vmja.sjvouefsb.org

mailing list:
chvmraphcewef <chvmraphcewef.3551601.xt.local>

mailed-by: merit-kitchens.com

signed-by: NETORGFT12811114.onmicrosoft.com

**Comment by andshiga** [comment]
Yeah, I noticed that yesterday too. I'll have to change the NETORG regex to catch NETORG* instead. This is so annoying...

**Comment by andshiga** [comment]
Done. Please check now.

**Comment by kokotas89** [comment]
Damn, do they really monitor Reddit... Or do they somehow find out cause of the reports. Anyway thanks for the fast reply, I will check as soon as I get back from work.

**Comment by kokotas89** [comment]
It's been working great so far! Thank you for staying on top of this.
